# custom-monitoring.yaml
$schema:  http://azureml/sdk-2-0/Schedule.json
name: my_custom_signal_cr
trigger:
  type: recurrence
  frequency: day # can be minute, hour, day, week, month
  interval: 7 # #every day
  schedule: 
    hours: 06 # at 3am
    minutes: 30 # at 15 mins after 3am

create_monitor:
  compute: 
    instance_type: standard_e4s_v3
    runtime_version: "3.3"

  monitoring_signals:
    customSignal:
      type: custom
      component_id: azureml:my_custom_signal_cr_2:1.0.0
      input_data:
        test_data_2:
          input_data:
            type: mltable
            path: azureml:direct:1
          data_context: test
          data_window:
            trailing_window_size: P30D
            trailing_window_offset: P7D
          pre_processing_component: azureml:custom_preprocessor_2:1.0.0
      metric_thresholds:
        - metric_name: std_dev
          threshold: 2
  alert_notification:
    emails:
      - raquelmo@microsoft.com