# custom-monitoring.yaml
$schema:  http://azureml/sdk-2-0/Schedule.json
name: my_custom_signal_cr
trigger:
  type: recurrence
  frequency: day # can be minute, hour, day, week, month
  interval: 7 # #every day
create_monitor:
  compute:
    instance_type: "standard_e8s_v3"
    runtime_version: "3.2"
  monitoring_signals:
    customSignal:
      type: custom
      component_id: azureml:my_custom_signal_cr:1.0.0
      input_data:
        test_data_2:
          input_data:
            type: mltable
            path: azureml:Direct:1
          data_context: test
          data_window:
            trailing_window_size: P30D
            trailing_window_offset: P7D
          pre_processing_component: azureml:custom_preprocessor_1:1.0.0
      metric_thresholds:
        - metric_name: std_dev
          threshold: 2
  alert_notification:
    emails:
      - raquelmo@microsoft.com