# custom-monitoring.yaml
$schema:  http://azureml/sdk-2-0/Schedule.json
name: custom_standard_deviation
trigger:
  type: recurrence
  frequency: day  # Can be minute, hour, day, week, month
  interval: 1     # 1 means every time unit (day)
  schedule:       # 08:15
    hours: 8      
    minutes: 15
create_monitor:
  compute:
    instance_type: "standard_e8s_v3"
    runtime_version: "3.3"
  monitoring_signals:
    custom_monitoring_signal:
      type: custom
      component_id: azureml:my_custom_signal_birds:1.0.0
      input_data:
        production_data:
          input_data:
            type: uri_folder
            path: "/subscriptions/e685500d-fd78-44fb-838b-07f8fc4c1fcf/resourceGroups/rg-amlws-dev/providers/Microsoft.MachineLearningServices/workspaces/amlws-dev/data/monit-online-bird-model-outputs-6/versions/1"
          data_context: model_inputs
            trailing_window_size: P30D
            trailing_window_offset: PT0S
          pre_processing_component: azureml:custom_preprocessor_birds:2.0.0
      metric_thresholds:
        - metric_name: std_deviation
          threshold: 2.0
  alert_notification:
    emails:
      - raquelmo@microsoft.com
