# custom-monitoring.yaml
$schema:  http://azureml/sdk-2-0/Schedule.json
name: my_custom_signal_cr
display_name: Fraud detection model monitoring Basic
description: Fraud detection model monitoring with advanced configurations

trigger:
  type: recurrence
  frequency: day # can be minute, hour, day, week, month
  interval: 7 # #every day
  schedule: 
    hours: 06 # at 3am
    minutes: 30 # at 15 mins after 3am

create_monitor:
  compute: 
    instance_type: standard_e4s_v3
    runtime_version: "3.3"

  monitoring_signals:
    customSignal:
      type: custom
      component_id: azureml:my_custom_signal_cr_3:1.0.0
      input_data:
        test_data_1:
          input_data:
            type: mltable
            path: azureml:azureml_3ff3b359-5724-49ac-aa21-1099dea4ad3a_output_data_preprocessed_input_data:1
          data_context: test
        test_data_2:
          input_data:
            type: mltable
            path: azureml:azureml_3ff3b359-5724-49ac-aa21-1099dea4ad3a_output_data_preprocessed_input_data:1
          data_context: test
          data_window:
            trailing_window_size: P30D
            trailing_window_offset: P7D
        #   pre_processing_component: azureml:custom_preprocessor:1.0.0
    metric_thresholds:
      - metric_name: std_dev
        threshold: 2      
  alert_notification:
    emails:
      - raquelmo@microsoft.com