$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: Component_pre_processing
description: Test pre processing

inputs:
  data_window_end: "2023-12-12T04:31:57.012Z"
  data_window_start: "2023-11-11T04:31:57.012Z"

outputs: 
  preprocessed_input_data:
    type: mltable
    mode: direct
  signal_metrics:
    type: mltable
    mode: direct

jobs:
  pre_process_job:
    type: spark
    component: azureml:custom_preprocessor_7@latest
    inputs:
      input_data: 
        type: uri_folder 
        path: azureml:sensor2:2
      data_window_end: ${{parent.inputs.data_window_end}}
      data_window_start: ${{parent.inputs.data_window_start}}
    outputs:
      preprocessed_input_data: ${{parent.outputs.preprocessed_input_data}}

    resources:
      instance_type: standard_e8s_v3
      runtime_version: "3.3"

  custom_signal:
    type: spark
    component: azureml:my_custom_signal_cr_3@latest
    inputs:
      production_data: 
        type: mltable
        mode: direct
        path: ${{parent.jobs.pre_process_job.outputs.preprocessed_input_data}}
      std_deviation_threshold: 1

    outputs:
      signal_metrics: ${{parent.outputs.signal_metrics}}

    resources:
      instance_type: standard_e8s_v3
      runtime_version: "3.3"