# model-monitoring-with-collected-data.yaml
$schema:  http://azureml/sdk-2-0/Schedule.json
name: fraud_detection_model_monitoring
display_name: Fraud detection model monitoring
description: Fraud detection model monitoring with your own production data

trigger:
  # perform model monitoring activity daily at 3:15am
  type: recurrence
  frequency: day #can be minute, hour, day, week, month
  interval: 1 # #every day
  schedule: 
    hours: 21 # at 3am
    minutes: 30 # at 15 mins after 3am

create_monitor:
  compute: 
    instance_type: standard_e4s_v3
    runtime_version: "3.3"

  monitoring_target:
    ml_task: classification
    endpoint_deployment_id: azureml:test-ml-studio-ldzji:credit-defaults-model-2
  
  monitoring_signals:
    advanced_data_drift: # monitoring signal name, any user defined name works
      type: data_drift
      # define production dataset with your collected data
      production_data:
        input_data:
          path: azureml:test-ml-studio-ldzji-credit-defaults-model-2-model_inputs:1  # your collected data is registered as Azure Machine Learning asset
          type: uri_folder
        data_context: model_inputs
        # pre_processing_component: azureml:production_data_preprocessing:1
      reference_data:
        input_data:
          path: azureml:creditcard_defaults:2.0.0 # use training data as comparison baseline
          type: uri_folder
        data_context: training
        target_column_name: Y
      features: 
        top_n_feature_importance: 20 # monitor drift for top 20 features
      metric_thresholds:
        categorical:
          pearsons_chi_squared_test: 0.02

  
  alert_notification:
    emails:
      - raquelmo@microsoft.com