$schema:  http://azureml/sdk-2-0/Schedule.json
name: my-custom-signal2
trigger:
  type: recurrence
  frequency: day # can be minute, hour, day, week, month
  interval: 7 # #every day
create_monitor:
  compute:
    instance_type: "standard_e8s_v3"
    runtime_version: "3.3"
  monitoring_signals:
    custom_monitoring_signal:
      type: custom
      alert_enabled: false
      component_id: azureml:custom_std_deviation:5
      input_data:
        production_data:
          input_data:
            type: uri_folder
            path: "azureml:/subscriptions/5fca341e-4ec3-45bd-b006-a7648d9376c5/resourceGroups/modelmonitoring-e2e-rg/providers/Microsoft.MachineLearningServices/workspaces/momo-e2e-test-ws-canary/data/cc_model_inputs/versions/1"
          data_context: model_inputs
          data_window:
            trailing_window_size: P1D
          pre_processing_component: "/subscriptions/5fca341e-4ec3-45bd-b006-a7648d9376c5/resourceGroups/modelmonitoring-e2e-rg/providers/Microsoft.MachineLearningServices/workspaces/momo-e2e-test-ws-canary/components/custom_signal_preprocessor/versions/1.0.0"
      inputs:
        production_data:
          path: azureml:cc_model_inputs:1
          type: uri_folder
      metric_thresholds:
      - metric_name: std_deviation
        threshold: 2.0
