$schema: http://azureml/sdk-2-0/OnlineDeployment.json
name: monitored
endpoint_name: ep-mon-birds
model: azureml:run-model-example:2
environment: azureml:AzureML-pytorch-1.9-ubuntu18.04-py37-cuda11-gpu@latest
instance_type: Standard_E4s_v3
instance_count: 1
egress_public_network_access: enabled
 
# Custom scoring script (optional for mlflow models, required for custom models)
code_configuration:
  code: .
  scoring_script: score.py
# Data collection for model monitoring
data_collector:
  collections:
    request:
      enabled: 'True'
      data:   #Custom location (optional)
        name: monit-online-bird-model-inputs-2
        path: azureml://datastores/workspaceblobstore/paths/modelDataCollector/cv-birds-monit-online-endp/bird-online-dp/model_inputs_1/
       
    response:
      enabled: 'True'
      data:  # Custom location (optional)
        name: monit-online-bird-model-outputs-2
        path: azureml://datastores/workspaceblobstore/paths/modelDataCollector/cv-birds-monit-online-endp/bird-online-dp/model_outputs_1/
