name: run-pipeline

on:
  workflow_call:
    inputs:
      parameters-file:
        required: true
        type: string
      resource_group:
        required: true
        type: string
      workspace_name:
        required: true
        type: string
      job-name:
        required: true
        type: string
    secrets:
      client_id:
      client_secret:
      subscription_id:
      tenant_id:

jobs:
  run-pipeline:
    runs-on: atc-ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Az CLI login'
        uses: azure/actions/login@v1
        with:
          creds: '{"clientId":"${{ secrets.client_id }}","clientSecret":"${{ secrets.client_secret }}","subscriptionId":"${{ secrets.subscription_id }}","tenantId":"${{ secrets.tenant_id }}"}'
      - name: install-extension
        run:  az extension add -n ml -y
      - name: update-extension
        run:  az extension update -n ml
      - name: run-ml-pipeline
        run: |
          az ml job create --file ${{ github.workspace }}/${{ inputs.parameters-file  }} --resource-group ${{ inputs.resource_group }} \
          --workspace-name ${{ inputs.workspace_name }} -o tsv --debug
