#State Management
state_resource_group: "rg-state-dev"
state_storage_account: "ststatedev02102023"

#User Config
subnet_name: "Subnet-3"
namespace: "dev"
postfix: "1"
location: "westeurope"
environment: "dev"
enable_aml_computecluster: true
enable_aml_secure_workspace: true
enable_monitoring: true
module_version: "feature/cv"

# clusters: {
#     cluster1 : {
#       name: "cpu-cluster",
#       vm_size: "STANDARD_DS3_V2",
#       min_node_count: 0,
#       max_node_count: 4,
#       scale_down_idle_time: "PT2M"
#     }
# }


#Dynamic names
resource_group: "rg-amlws-dev"
storage_account: "stamlwsdev02102023"
container_name: "terraform-state"
key_vault: "keyvault09102023"
container_registry: "crdev24092023"
app_insights: "appdev-2"
batch_endpoint_name: "ep-${namespace}-${environment}-${postfix}"
online_endpoint_name: "oe-${namespace}-${environment}-${postfix}"
aml_workspace: "amlws-dev"

#Selective Modules:
#Select the modules to deploy by setting them to true or false if 
#the module should not be deployed as part of the infrastructure
monitoring: false
logic_apps: false


 
