#User Config
location: "westeurope"
environment: "dev"
namespace: "cv-model"
enable_aml_computecluster: true
enable_aml_secure_workspace: true
enable_monitoring: true

#Dynamic names
resource_group: "caixa-tests"
storage_account: "sacaixatest"
key_vault: "testmlstudio1319267772"
container_registry: "6ac3d818ab594971b107affa8641f52c"
app_insights: "testmlstudio9536849072"
# batch_endpoint_name: "ep-${namespace}-${environment}"
# online_endpoint_name: "oe-${namespace}-${environment}"
aml_workspace: "test-ml-studio"

#Selective Modules:
monitoring: false
logic_apps: false


 
