name: monitoring

on:
  workflow_call:
    inputs:
      custom_signal_file:
        required: true
        type: string
      resource_group:
        required: true
        type: string
      workspace_name:
        required: true
        type: string
      custom_monitoring_file:
        required: false
        default: ''
        type: string
      basic_monitoring_file:
        required: false
        default: ''
        type: string        
      custom_signal_prepro:
        required: false
        default: ''
        type: string
      custom_monitoring_signal:
        required: false
        default: ''
        type: string
      custom_job_file:
        required: false
        default: ''
        type: string                       
      cli_version:
        required: false
        default: '2.21.0'
        type: string
    secrets:
      client_id:
      client_secret:
      subscription_id:
      tenant_id:
jobs:
  register-environment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: 'Az CLI login'
        uses: azure/actions/login@v1
        with:
          creds: '{"clientId":"${{ secrets.client_id }}","clientSecret":"${{ secrets.client_secret }}","subscriptionId":"${{ secrets.subscription_id }}","tenantId":"${{ secrets.tenant_id }}"}'    
      - name: install-extension
        run:  az extension add -n ml --version ${{ inputs.cli_version}} -y
      - name: update-extension
        run: az extension update -n ml
      - name: list-extentions
        run: az extension list
      - name: custom-signal-preproc
        run: |
          az ml component create --file ${{ github.workspace }}/${{ inputs.custom_signal_prepro }} --resource-group ${{ inputs.resource_group }} --workspace-name ${{ inputs.workspace_name }}
      # - name: custom-signal-component
      #   run: |
      #     az ml component create --file ${{ github.workspace }}/${{ inputs.custom_signal_file }} --resource-group ${{ inputs.resource_group }} --workspace-name ${{ inputs.workspace_name }}
      # - name: create-monitor-basic
      #   run: |
      #     az ml schedule create --file ${{ github.workspace }}/${{ inputs.basic_monitoring_file }} --resource-group ${{ inputs.resource_group }} --workspace-name ${{ inputs.workspace_name }} --debug
      # - name: create-monitor-advanced
      #   run: |
      #     az ml schedule create --file ${{ github.workspace }}/${{ inputs.custom_monitoring_file }} --resource-group ${{ inputs.resource_group }} --workspace-name ${{ inputs.workspace_name }} --debug
      - name: job-pre-proc
        run: |
          az ml job create --file ${{ github.workspace }}/${{ inputs.custom_job_file }} --resource-group ${{ inputs.resource_group }} --workspace-name ${{ inputs.workspace_name }} --debug
      - name: create-monitor-custom-signal
        run: |
          az ml schedule create --file ${{ github.workspace }}/${{ inputs.custom_monitoring_signal }} --resource-group ${{ inputs.resource_group }} --workspace-name ${{ inputs.workspace_name }} --debug                              