name: register-environment

on:
  workflow_call:
    inputs:
      environment_file:
        required: true
        type: string
      resource_group:
        required: true
        type: string
      workspace_name:
        required: true
        type: string
      conda_file:
        required: false
        default: ''
        type: string
    secrets:
      client_id:
      client_secret:
      subscription_id:
      tenant_id:
jobs:
  register-environment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: 'Az CLI login'
        uses: azure/actions/login@v1
        with:
          creds: '{"clientId":"${{ secrets.client_id }}","clientSecret":"${{ secrets.client_secret }}","subscriptionId":"${{ secrets.subscription_id }}","tenantId":"${{ secrets.tenant_id }}"}'    
      - name: install-extension
        run:  az extension add -n ml -y
      - name: update-extension
        run: az extension update -n ml
      - name: list-extentions
        run: az extension list
      - name: create-environment-from-file-with-conda
        if: ${{ inputs.conda_file != ''}}
        run: |
          az ml environment create --file ${{ github.workspace }}/${{ inputs.environment_file }} --resource-group ${{ inputs.resource_group }} \
                                --workspace-name ${{ inputs.workspace_name }} --conda-file ${{ github.workspace }}/${{ inputs.conda_file }}
      - name: create-environment-from-file-without-conda
        if: ${{ inputs.conda_file == ''}}
        run: |
          az ml environment create --file ${{ github.workspace }}/${{ inputs.environment_file }} --resource-group ${{ inputs.resource_group }} \
                                  --workspace-name ${{ inputs.workspace_name }}
